# Generated by Django 5.2.7 on 2025-10-10 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_feeding_options_feeding_cat_alter_cat_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeding',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedings', to='main_app.cat'),
        ),
    ]
